version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - node/install-packages
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - node/install-packages
      - run: npm install
      - deploy:
          name: Deploy to Production
          command: npm start

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main